# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjR0zih1ec8HZ-kpiz01cMMo5dibKbsw
"""

import streamlit as st
import pickle
import re

# Load Model dan TF-IDF
model = pickle.load(open("model.pkl", "rb"))
tfidf = pickle.load(open("tfidf.pkl", "rb"))

# Fungsi cleaning
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

# UI Streamlit
st.title("Amazon Review Sentiment Analysis")
st.write("Masukkan review produk Amazon untuk mengetahui sentimennya.")

input_text = st.text_area("Masukkan Review:")

if st.button("Prediksi"):
    cleaned = clean_text(input_text)
    vector = tfidf.transform([cleaned])
    prediction = model.predict(vector)[0]

    st.subheader("Hasil Prediksi Sentimen:")
    st.success(prediction)